### ISSUE TITLE
server certificate verification failed

### ISSUE THREAD

**Issue by xcopy** [Mashape/unirest-php#103]
Something goes wrong in Travis CI: my tests failed

```
Unirest\Exception: server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
vendor/mashape/unirest-php/src/Unirest/Request.php:475
vendor/mashape/unirest-php/src/Unirest/Request.php:239
```

Please can you take a look at failed build: https://travis-ci.org/xcopy/dieselup/builds/123015560

Or am I missing something?

**Comment by ahmadnassri** [comment]
@xcopy hey there, sorry for the delay, did you figure this out?

**Comment by xcopy** [comment]
@ahmadnassri Nope, still don't know what's the problem.

**Comment by ahmadnassri** [comment]
The basic reason is that the Travis servers on-which this test is running doesn't seem to trust the certificate authority that signed the certificate used on the API server. 

This doesn't mean the certificate is suspicious, but it could be self-signed or signed by an institution/company that isn't in the list of the OS's list of CAs. 

What you have to do to circumvent the problem on Travis is telling it to trust that certificate (if you don't have any reason to be suspicious about it.)
