### ISSUE TITLE
Uncaught exception 'Unirest\Exception'

### ISSUE THREAD

**Issue by bishu** [Mashape/unirest-php#107]
Sir,
 
I am very new to PHP and the mashape api. I am using WAMPServer.
 
I would like to use some of the API provided by mashape but unable to integrate to my PHP website.
I have download the unirest-php-master and put in the includes folder.
 
I write the code as
```php
<?PHP
require_once 'includes/unirest-php-master/src/Unirest.php';
$response = Unirest\Request::get("https://dndcheck.p.mashape.com/index.php?mobilenos=9999999999",
  array(
    "X-Mashape-Key" => My Key here
    "Accept" => "application/json"
  )
);
 
echo json_encode($response->body);
 
?>
 ```
I got an error as
Fatal error: Uncaught exception 'Unirest\Exception' with message 'SSL certificate problem: unable to get local issuer certificate' in C:\wamp\www\xxxxx\includes\unirest-php-master\src\Unirest\Request.php on line 475 
( ! ) Unirest\Exception: SSL certificate problem: unable to get local issuer certificate in C:\wamp\www\xxxxx\includes\unirest-php-master\src\Unirest\Request.php on line 475 

I am very confuse what I have miss out.

**Comment by irfanevrens** [comment]
Use like this.
`$response = \Unirest\Request::get(bla bla bla)`
