### ISSUE TITLE
Asynchronous requests

### ISSUE THREAD

**Issue by subnetmarco** [Mashape/unirest-php#23]
I would really like to add asynchronous request support to Unirest-PHP, so that it can match the feature set of the other Unirest libraries (http://unirest.io).

PHP doesn't natively support threads, and it doesn't seem to be a standard practice for achieving this. I would like to encourage a discussion to share some ideas for a possible async implementation.

**Comment by ahmadnassri** [comment]
closing this, until a PR is made.
