### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by mattarnster** [Mashape/unirest-php#27]
Hi there, trying to use this with the Mashape API, and get this lovely exception when trying to make a request to an API endpoint:

Fatal error: Uncaught exception 'Exception' with message 'SSL certificate problem: self signed certificate in certificate chain' in C:****_\unirest\lib\Unirest\Unirest.php:166 Stack trace: #0 C:\**_**\unirest\lib\Unirest\Unirest.php(47): Unirest::request('GET', 'https://yoda.p....', NULL, Array, NULL, NULL) #1 C:\****_\yoda.php(9): Unirest::get('https://yoda.p....', Array, NULL) #2 {main} thrown in C:\**_**\unirest\lib\Unirest\Unirest.php on line 166

**Comment by JefferyHus** [comment]
whom ever is facing this issue try this:
```php
\Unirest\Request::verifyPeer(false);
```

**Comment by javase** [comment]
the version I use unirest is 3.1.02,
maven config is :
<dependency>
   <groupId>com.konghq</groupId>
   <artifactId>unirest-java</artifactId>
   <version>3.1.02</version>
   <classifier>standalone</classifier>
</dependency>
and I see kong.unirest.UnirestException: javax.net.ssl.SSLHandshakeException。
when I config "Unirest.config().verifySsl(false);" it works ,the exception disappear

**Comment by javase** [comment]
the version I use unirest is 3.1.02,
maven config is :
`
<dependency>
   <groupId>com.konghq</groupId>
   <artifactId>unirest-java</artifactId>
   <version>3.1.02</version>
   <classifier>standalone</classifier>
</dependency>
`
and I see `kong.unirest.UnirestException: javax.net.ssl.SSLHandshakeException`。
when I config `"Unirest.config().verifySsl(false);"` it works ,the exception disappear
