### ISSUE TITLE
Unirest doesn't automatically store cookies to send them on subsequent requests

### ISSUE THREAD

**Issue by bitliner** [Mashape/unirest-php#35]
I'm submitting a GET request with Unirest to my server.

The url of this GET request contains a token (it is needed to authorize the request). The server checks if this token is in the session, if it is the request is authorized.

The problem is that if I submit the request with Unirest the request is unauthorized.
If I take the same url, with the same token, and I submit this url to the browser, the request is authorized and the response is returned.

It's like Unirest makes some manipulation on the url string.

Do you have some clue to explain this behaviour?

**Comment by ahmadnassri** [comment]
hoping that #47 will take care of this, will check again after that PR is updated with new code structure.
