### ISSUE TITLE
Errors from time to time

### ISSUE THREAD

**Issue by Lechus** [Mashape/unirest-php#42]
curl_setopt(): The usage of the @filename API for file uploading is deprecated. Please use the CURLFile class instead 

line 187: 
```
curl_setopt($ch, CURLOPT_POSTFIELDS, $postBody);
```
I use it with Laravel 4.1 (up2date), PHP 5.5.11-3+deb.sury.org~precise+1

**Comment by ahmadnassri** [comment]
@Lechus we are indeed using CURLFile now (if supported by your system)
