### ISSUE TITLE
Arrays in GET string are corrupted

### ISSUE THREAD

**Issue by Tallowman** [Mashape/unirest-php#46]
When passing through a query with an array parameter in the GET string, for example,

?user_id[]=1&user_id[]=2

I am only getting the results for user_id = 2. When I look in the result object, I see my results for user_id=2 repeated twice.

When I look in the raw_body, I see only one result ( user_id=2 ).

When using file_get_contents with the same query, I get both results as expected. I have tried with multiple parameters and my server code with file_get_contents handles the request as expected.

I suspect that somehow a query with:
 "?user_id[]=1&user_id[]=2" 

is somehow getting parsed as "?user_id[]=2&user_id[]=2".

The same effect happens with three parameters - 

 "?user_id[]=1&user_id[]=2&user_id[]=3" will only return the results for user_id = 3.

**Comment by ahmadnassri** [comment]
@Tallowman this has been fixed in the much improved v2.0.0 please give it a try and let us know!
