### ISSUE TITLE
PHP Error: Undefined offset

### ISSUE THREAD

**Issue by danger89** [Mashape/unirest-php#52]
Hi folks,

I got a lot of time the following error message from PHP:
PHP Notice:  Undefined offset: 1 in Unirest/Unirest.php on line 239

Please take a look at this line.

Thanks!

Kind regards,
Melroy van den Berg

**Comment by ahmadnassri** [comment]
@danger89 this should be addressed in the new release, can you please confirm if this is still an issue?
