### ISSUE TITLE
Get HTTP Code when Exception in Response

### ISSUE THREAD

**Issue by vmartins** [Mashape/unirest-php#66]
How to get the http code when catch exception in response?

**Comment by ahmadnassri** [comment]
hey @vmartins can you explain where you're getting the exception?

**Comment by vmartins** [comment]
I know my request returns 302 (in some cases), but can not detect the http code, because in Exception (try/catch) I do not get the request code.
The Exception returns the message 'Empty reply from server', but not the http code.

**Comment by ahmadnassri** [comment]
@vmartins it is now possible to better debug failed requests with `Unirest\Request::getInfo()` in [v2.3.0](https://github.com/Mashape/unirest-php/releases/tag/v2.3.0) 

*see [curl_getinfo](http://php.net/manual/en/function.curl-getinfo.php)*
