### ISSUE TITLE
how to use API mashape with PHP unirest

### ISSUE THREAD

**Issue by mrjas** [Mashape/unirest-php#69]
i have problems with php unirest pls help me . i have code :

require_once 'vendor/autoload.php'; 
Unirest\Request::verifyPeer(false);
 $response = Unirest\Request::post("https://savedeo.p.mashape.com/download",
  array(
    "X-Mashape-Key" => "Mykey",
    "Content-Type" => "application/x-www-form-urlencoded",
    "Accept" => "application/json"
  ),
  array(
    "url" => "https://vimeo.com/87374427"
  )
);
print_r($response);
 ?>

and i have Revice error : 

Unirest\Response Object ( [code] => 403 [raw_body] => {"message": "Invalid url: None"} [body] => stdClass Object ( [message] => Invalid url: None ) [headers] => Array ( [0] => HTTP/1.1 403 FORBIDDEN [Content-Type] => application/json [Date] => Sun, 08 Feb 2015 13:12:52 GMT [Server] => Mashape/5.0.6 [X-RateLimit-requests-Limit] => 200 [X-RateLimit-requests-Remaining] => 189 [Content-Length] => 32 [Connection] => keep-alive ) )

How to fix it .... Pls help my thank so much

**Comment by thibaultCha** [comment]
This issue belongs more on StackOverflow. Use the `#unirest` tag.
