### ISSUE TITLE
Operation Timeout error when using Unirest::timeout(5)

### ISSUE THREAD

**Issue by khurshid-alam** [Mashape/unirest-php#71]
My app on heroku uses unirest library(`v 1.2.1`) for http requests. When I make a `HTTP POST` request to a remote script I set  `Unirest::timeout(5)` (because I don't care about data returning from request).

But if it fails to get the data from the request, it complains about: `Operation timed out after 5000 milliseconds with 0 bytes received` and some times it **doesn't** even process the remote script.

How do I get rid of that error message? Or is there a better way to achieve this?

Thanks.

**Comment by ahmadnassri** [comment]
safest way is to put it behind `try {} catch() {}` block, Unirest-php uses the native [PHP cURL extension](http://php.net/manual/en/book.curl.php) so what you're seeing is an exception thrown on the cURL php extension level.
