### ISSUE TITLE
Unirest not being found by Laravel

### ISSUE THREAD

**Issue by Tallowman** [Mashape/unirest-php#74]
Hi,

I've returned to an Laravel application having not worked on it since October 2014. I am using a different laptop, and have pulled my repo from git, only to find that Unirest class is not found in my app anymore. 

I have checked and double checked my composer.json files, and ran update several times, but there is no success. My colleague has just run a composer self-update, and it seems his app is now broken with the same error - not being able to find Unirest. There are no problems with any other dependancies. 

Are there any known issues around this? We are using Laravel 4.2

**Comment by ahmadnassri** [comment]
since version 2.0 Unirest is now a namespace and the class you're looking for is `Unirest\Request`

**Comment by Tallowman** [comment]
Cheers :) That does the trick.
