### ISSUE TITLE
Always get 403

### ISSUE THREAD

**Issue by ukebako** [Mashape/unirest-php#80]
Hi.
When I call API from php using unirest, I always get 403 error.
I have copied and paste the code from API page, including my API key.
Console curl works well.

**Comment by ahmadnassri** [comment]
can you post the example here?

**Comment by ukebako** [comment]
Hi
I run the following code:
```php
$response = \Unirest\Request::post("https://community-neutrino-ip-info.p.mashape.com/ip-info",
          array(
            "X-Mashape-Key" => "...",
            "Content-Type" => "application/x-www-form-urlencoded",
            "Accept" => "application/json"
          ),
          array(
            "ip" => "93.75.23.180",
            "reverse-lookup" => false
          )
      );
```
And get 403 error.
I copied the code without changes from API page.
I also tried to use php curl, but got the same error.

But the console curl works.
