### ISSUE TITLE
curl_setopt_array()

### ISSUE THREAD

**Issue by gestudio** [Mashape/unirest-php#85]
curl_setopt_array(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set...

[ROOT/vendors/unirest/src/Unirest/Request.php, line 423]

**Comment by ahmadnassri** [comment]
http://stackoverflow.com/questions/6918623/curlopt-followlocation-cannot-be-activated

**Comment by gestudio** [comment]
I dont think just turning the open_basedir off is a solution. I will switch to other library over time, to be able to enable it again.

**Comment by ahmadnassri** [comment]
I realize, that's not really the answer you wanted, but it seems to be outside the scope of the library ... this is a problem on PHP/cURL level.

**Comment by ahmadnassri** [comment]
we can add an option to disable following redirects and that would remove the `CURLOPT_FOLLOWLOCATION` call, which could solve your problem, but then you can't follow redirects :)

**Comment by gestudio** [comment]
ummm, I think it should be an option yes.

Anyway, Ive started to use the Cakephp's HTTP socket class, its working fine for me + redirects, and it does not required to disabled openbase_dir restriction, so, I am going to switch all the calls and remove Unirest, thanks for the support.
