### ISSUE TITLE
403

### ISSUE THREAD

**Issue by garrylachman** [Mashape/unirest-php#87]
Always get 403 error, its works with CURL but Unirest is not working
i try from CLI and from WebServer

here is the code:
$response = Unirest\Request::post("https://community-neutrino-ip-info.p.mashape.com/ip-info",
  array(
    "X-Mashape-Key" => "XXXX",
    "Content-Type" => "application/x-www-form-urlencoded",
    "Accept" => "application/json"
  ),
  array(
    "ip" => "5.29.224.80",
    "reverse-lookup" => true
  )
);

**Comment by ahmadnassri** [comment]
this is now fixed in [`v3.0.0`][release]

**PLEASE NOTE**: `v3.0.0` introduces API changes, please review the [release notes][release] and [README](https://github.com/Mashape/unirest-php/blob/master/README.md) for details

[release]: https://github.com/Mashape/unirest-php/releases/tag/v3.0.0

**Comment by polykrom** [comment]
I don't know if it's fixed ... tested with version 3.0.0 of the lib and getting always 403 forbidden errors for Mashape : 

```
require_once 'vendor/autoload.php';

global $url;
$url = $_GET['url'];


$response = Unirest\Request::post("https://savedeo.p.mashape.com/download",
  array(
    "X-Mashape-Key" => "e6PtbYC3OCmshFHUdKo0BucN29p9p1EE3idjsnRuyrQTgiLtJs",
    "Content-Type" => "application/x-www-form-urlencoded",
    "Accept" => "application/json"
  ),
  array(
    "url" => urlencode($url)
  )
);
```

Any idea ??

**Comment by polykrom** [comment]
Ok... didn't read the new README ...

works with : 

```
global $url;
$url = $_GET['url'];


$data =   array(
    "url" => $url
  );

$body = Unirest\Request\Body::form($data);

$response = Unirest\Request::post("https://savedeo.p.mashape.com/download",
  array(
    "X-Mashape-Key" => "KEY",
    "Content-Type" => "application/x-www-form-urlencoded",
    "Accept" => "application/json"
  ),
  $body
);

echo $response;
```

**Comment by ahmadnassri** [comment]
awesome :+1:

**Comment by sinzone** [comment]
:rocket:
