### ISSUE TITLE
"Missing Mashape application key." even with my API key

### ISSUE THREAD

**Issue by ungabo** [Mashape/unirest-php#94]
Shashi Ranjan at Mashape support suggested I request your help and said he cc'd you on the issue already.

I keep getting this error when I do a get, and I'm getting no response with my post:
Missing Mashape application key. Go to http:\\\/\\\/docs.mashape.com\\\/api-keys to learn how to get your API application key.\
I've put in my application key, I got it, put it in, should be good.

I am using the pdf2jpg api.
I'm trying to convert the file:
http://patersonconnect.com/_img/text.pdf  (you can see it's there).
I'm running this script from the same folder.  You can run it yourself:
http://patersonconnect.com/_img/x1.php

here's what's in it:
```php
<?php
// Report all PHP errors
error_reporting(-1);

// Same as error_reporting(E_ALL);
ini_set('error_reporting', E_ALL);

require_once 'src/Unirest.php';
echo '<br>start: ';
// These code snippets use an open-source library. http://unirest.io/php
$response = Unirest\Request::post("https://pdf2jpg-pdf2jpg.p.mashape.com/convert_pdf_to_jpg.php",
  array(
    "X-Mashape-Key" => "I use my API key but don't want to post it here"
  ),
  array(
    "pdf" => Unirest\file::add("text.pdf"),
    "resolution" => 300
  )
);

echo json_encode($response);
?>
```
I'm not getting any errors, just nothing.

I also have a second script which runs the "get" here.  I can't put in the necessary response key's from the first script as they are not appearing, but I still shouldn't be getting an issue with the API key, right?
```php
<?php
echo 'response:<br>';

require_once 'src/Unirest.php';
// These code snippets use an open-source library. http://unirest.io/php
$response = Unirest\Request::get("https://pdf2jpg-pdf2jpg.p.mashape.com/convert_pdf_to_jpg.php?id=8084&key=8f1c364d1be4e0a951e67e652cc25325e0dbdff7",
  array(
    "X-Mashape-Key" => "I use my API key but don't want to post it here",
    "Accept" => "application/json"
  )
);

var_dump($response);
?>
```
You can run this script for yourself here:http://patersonconnect.com/_img/x2.php

Why would be getting this error?  It shouldn't be an SSL thing, right?
Please help.
Thank you.

**Comment by ahmadnassri** [comment]
@ungabo what version of unirest-php are you using? please note [v3.0.0](https://github.com/Mashape/unirest-php/releases/tag/v3.0.0) introduces [breaking changes for post requests](https://github.com/Mashape/unirest-php/blob/master/README.md#form-requests-applicationx-www-form-urlencoded), making the code you shared above wrong.

**Comment by ungabo** [comment]
Ah!  That must  be it.  I got the code off the mashape site but i do have the latest version of unirest which is 3. 
Would you mind sending me a modification od my code to work with unirest 3?  I'm sure this would also be useful for the mashape api doc page. 
I'm not familiar with unirest.  Just am using it for this api.  I appreciate the help. 
Thanks. 


Sent from Yahoo Mail on Android 
 
  On Wed, Mar 9, 2016 at 9:41 AM, Ahmad Nassri<notifications@github.com> wrote:   
@ungabo what version of unirest-php are you using? please note v3.0.0 introduces breaking changes for post requests, making the code you shared above wrong.

**Comment by ahmadnassri** [comment]
you can find all the details in the updated docs on the README.
