### ISSUE TITLE
Fatal error: Class 'Unirest\File' not found

### ISSUE THREAD

**Issue by atheimer** [Mashape/unirest-php#95]
Using latest files but running into issues calling the File function.  Below is my usage:

$body = array("content" => Unirest\File::add("/emails/basic.html");
$response = Unirest\Request::post($GLOBALS['restUrl'], $headers = '', $body);

**Comment by ahmadnassri** [comment]
The API changed with `v3.0.0`, please review the README for details, but essentially:


simply add an array of files as the second argument to to the Multipart helper:

```php
$headers = array('Accept' => 'application/json');
$data = array('name' => 'ahmad', 'company' => 'mashape');
$files = array('bio' => '/path/to/bio.txt', 'avatar' => '/path/to/avatar.jpg');

$body = Unirest\Request\Body::multipart($data, $files);

$response = Unirest\Request::post('http://mockbin.com/request', $headers, $body);
```

If you wish to further customize the properties of files uploaded you can do so with the `Unirest\Request\Body::File` helper:

```php
$headers = array('Accept' => 'application/json');
$body = array(
    'name' => 'ahmad', 
    'company' => 'mashape'
    'bio' => Unirest\Request\Body::file('/path/to/bio.txt', 'text/plain'),
    'avatar' => Unirest\Request\Body::file('/path/to/my_avatar.jpg', 'text/plain', 'avatar.jpg')
);

$response = Unirest\Request::post('http://mockbin.com/request', $headers, $body);
```
