### ISSUE TITLE
FatalErrorException in Unirest.php line 216: Maximum execution time of 60 seconds exceeded

### ISSUE THREAD

**Issue by eiyu** [Mashape/unirest-php#96]
I'd like to load big data and my internet connention is slow, how to add an additional time or change the timeout to maximize excecution time?
Thanks in advance.

**Comment by ahmadnassri** [comment]
you can control the timeout for Unirest itself with the [`timeout`](https://github.com/Mashape/unirest-php#timeout) method.

Also don't forget to enlarge time execution of php script self:

```php
set_time_limit(0); // to infinity for example
```

**Comment by eiyu** [comment]
okay, thank you @ahmadnassri 
I just missed that one out.
