### ISSUE TITLE
how to use the timeout method?

### ISSUE THREAD

**Issue by eiyu** [Mashape/unirest-php#97]
How do we use Unirest timeout method, I have this code but its not working

     public function __construct($api_key, $additional_headers = array()) {
            Unirest::timeout(200);
            AbcClass::$api_key = $api_key;
            Unirest::defaultHeader("Content-Type", "application/x-www-form-urlencoded");
            Unirest::defaultHeader("key", AbcClass::$api_key);
            foreach ($additional_headers as $key => $value) {
            Unirest::defaultHeader($key, $value);

            }
        }

I also try

        function getCost($origin, $destination = array(),$weight, $courier = NULL) {
        Unirest::timeout(200);
        $params = array(
            'origin' => $origin,
            'destination' => $destination,
            'weight' => $weight
        );
        if (!is_null($courier)) {
            $params['courier'] = $courier;
        }
        
        return Unirest::post(AbcClass::$base_url . "cost", array(), http_build_query($params));
    }
}

**Comment by ahmadnassri** [comment]
I suggest you review the README docs again, your code for making a POST request is wrong.

**Comment by eiyu** [comment]
Hi, Thank you again @ahmadnassri,  i've try to put the timeout method in the constructor and it doesn't work and then actually I have no idea where to put the timeout method again, 
maybe this code is not good practice but check this out (i'm using laravel)

        // get all shipping cost from one city to every city
        Route::get('/{origin}/{courier}', function ($origin,$courier) {

        $client = new AbcClass("apikey");

        $cities = $client->getCity();
        $body = $cities->body;
        //get allcity array
        $allCity = $body->abcapi->results;
        //make new post request for each city
        foreach ($allCity as $city) {
	$costs = $client->getCost($origin, $city->city_id, 1000, $courier);
        $value = $costs->body;
	$cost = $value->abcapi->results[0]->costs[0]->cost[0]->value;

	echo $city->city_id . "," . $city->city_name . "," . $cost . "<br/>";
     }

the code is working but it stops in the middle because of maximum exceed 60 sec.
Do you have suggestion?
Sorry for asking this in here.

**Comment by ahmadnassri** [comment]
https://github.com/Mashape/unirest-php#form-requests-applicationx-www-form-urlencoded

**Comment by ahmadnassri** [comment]
sounds like the time out on the PHP level is still triggering, not unirest.
